apiversion: apps/va
kind: Deployment
metadata:
  name: helloworldapp
  labels:
    app: helloworldapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldapp
    template:
      metadata:
        labels:
          app: helloworldapp
      spec:
        containers:
        - name: helloworldapp
          image: {{ .Values.appimage}}: {{ .values.apptag}}
          ports:
          - name: helloworld-port
            containerPort: 8001